// DO NOT EDIT
// Generated by JFlex 1.9.0 http://jflex.de/
// source: LexerPrueba.jflex

package com.yefrig.boxworldserver.parser;
import java_cup.runtime.*;
/*Primer seccion  codigo de usuario*/


@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\5\u0100\1\u0200\1\u0300\1\u0100\5\u0400\1\u0500\1\u0600"+
    "\1\u0700\6\u0100\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00"+
    "\211\u0100\1\u0600\1\u0100\1\u0e00\1\u0f00\1\u1000\1\u1100\123\u0100"+
    "\1\u0900\4\u0100\1\u1200\10\u0100\1\u1300\2\u0100\1\u1400\1\u1500"+
    "\1\u1100\1\u0100\1\u0500\1\u0100\1\u1600\1\u1300\1\u0800\3\u0100"+
    "\1\u1000\1\u1700\114\u0100\1\u1800\1\u1000\153\u0100\1\u1900\11\u0100"+
    "\1\u1a00\1\u1100\6\u0100\1\u1000\u0f16\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\0\1\4\1\5\4\0\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\11\17\1\20\6\0"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\27\1\32\1\33\2\27\1\34\2\27\1\35"+
    "\5\27\1\36\1\37\1\27\1\40\1\0\1\41\1\0"+
    "\1\42\1\0\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\27\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\27\1\62\1\63\1\64\1\65\1\27"+
    "\1\66\1\67\1\70\1\27\1\71\1\72\1\73\u01e2\0"+
    "\12\74\206\0\12\74\306\0\12\74\234\0\12\74\166\0"+
    "\12\74\140\0\12\74\166\0\12\74\106\0\12\74\u0116\0"+
    "\12\74\106\0\12\74\u0146\0\12\74\46\0\12\74\u012c\0"+
    "\12\74\200\0\12\74\246\0\12\74\6\0\12\74\266\0"+
    "\12\74\126\0\12\74\206\0\12\74\6\0\12\74\u0176\0"+
    "\12\74\46\0\12\74\306\0\12\74\26\0\12\74\126\0"+
    "\12\74\u0196\0\12\74\246\0\12\74\206\0\12\74\u012c\0"+
    "\12\74\200\0\12\74\74\0\12\74\220\0\12\74\166\0"+
    "\12\74\146\0\12\74\206\0\12\74\106\0\12\74\266\0"+
    "\12\74\u0164\0\62\74\100\0\12\74\266\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[6912];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\2\13\1\14\2\1\1\15"+
    "\1\16\1\17\1\20\13\0\1\21\21\0\1\22\2\0"+
    "\1\23\17\0\1\24\22\0\1\25\1\0\1\26\5\0"+
    "\1\27\2\0\1\30\1\0\1\31\1\32\1\33\1\0"+
    "\1\34\1\0\1\35\1\36\2\0\1\37\11\0\1\40"+
    "\1\0\1\41\12\0\1\42\10\0\1\43\10\0\1\44"+
    "\4\0\1\45\4\0\1\46\1\47\6\0\1\50\3\0"+
    "\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[176];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\75\0\172\0\267\0\364\0\75\0\75"+
    "\0\75\0\75\0\75\0\75\0\75\0\u0131\0\u016e\0\75"+
    "\0\u01ab\0\u01e8\0\75\0\75\0\75\0\75\0\u0225\0\u0262"+
    "\0\u029f\0\u02dc\0\u0319\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a"+
    "\0\u0487\0\364\0\u04c4\0\u0501\0\u053e\0\u057b\0\u05b8\0\u05f5"+
    "\0\u0632\0\u066f\0\u06ac\0\u06e9\0\u0726\0\u0763\0\u07a0\0\u07dd"+
    "\0\u081a\0\u0857\0\u0894\0\u04c4\0\u08d1\0\u090e\0\75\0\u094b"+
    "\0\u0988\0\u09c5\0\u0a02\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33"+
    "\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\u0c64\0\u0ca1\0\75\0\u0cde"+
    "\0\u0d1b\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6"+
    "\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae"+
    "\0\u10eb\0\75\0\u1128\0\75\0\u1165\0\u11a2\0\u11df\0\u121c"+
    "\0\u1259\0\75\0\u1296\0\u12d3\0\75\0\u1310\0\75\0\75"+
    "\0\75\0\u134d\0\75\0\u138a\0\75\0\75\0\u13c7\0\u1404"+
    "\0\75\0\u1441\0\u147e\0\u14bb\0\u14f8\0\u1535\0\u1572\0\u15af"+
    "\0\u15ec\0\u1629\0\75\0\u1666\0\75\0\u16a3\0\u16e0\0\u171d"+
    "\0\u175a\0\u1797\0\u17d4\0\u1811\0\u184e\0\u188b\0\u18c8\0\75"+
    "\0\u1905\0\u1942\0\u197f\0\u19bc\0\u19f9\0\u1a36\0\u1a73\0\u1ab0"+
    "\0\75\0\u1aed\0\u1b2a\0\u1b67\0\u1ba4\0\u1be1\0\u1c1e\0\u1c5b"+
    "\0\u1c98\0\75\0\u1cd5\0\u1d12\0\u1d4f\0\u1d8c\0\75\0\u1dc9"+
    "\0\u1e06\0\u1e43\0\u1e80\0\75\0\75\0\u1ebd\0\u1efa\0\u1f37"+
    "\0\u1f74\0\u1fb1\0\u1fee\0\75\0\u202b\0\u2068\0\u20a5\0\75";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[176];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\2\1\15\1\16\1\17\1\20"+
    "\2\2\1\21\2\2\1\22\11\2\1\23\1\24\27\2"+
    "\1\25\1\2\1\26\1\2\77\0\1\3\113\0\1\27"+
    "\1\30\5\27\1\31\7\27\2\0\2\27\1\32\1\33"+
    "\4\27\1\34\4\27\1\35\1\27\1\36\1\37\1\27"+
    "\1\40\1\41\3\27\1\0\1\27\20\0\2\42\1\0"+
    "\6\42\14\0\6\42\40\0\1\43\74\0\1\43\1\0"+
    "\2\17\102\0\1\44\102\0\1\45\62\0\17\46\3\0"+
    "\26\46\25\0\14\46\1\47\2\46\3\0\26\46\25\0"+
    "\1\50\16\46\3\0\26\46\25\0\17\46\3\0\15\46"+
    "\1\51\1\46\1\52\6\46\25\0\17\46\3\0\15\46"+
    "\1\53\10\46\25\0\17\46\3\0\1\54\25\46\25\0"+
    "\17\46\3\0\1\55\25\46\25\0\17\46\3\0\12\46"+
    "\1\56\2\46\1\57\10\46\25\0\17\46\3\0\15\46"+
    "\1\60\10\46\25\0\17\46\3\0\1\61\24\46\1\62"+
    "\25\0\17\46\3\0\14\46\1\63\11\46\22\0\2\64"+
    "\54\0\1\64\31\0\1\65\77\0\1\66\44\0\1\67"+
    "\11\0\2\46\1\0\17\46\3\0\26\46\10\0\1\67"+
    "\11\0\2\46\1\0\10\46\1\70\6\46\3\0\26\46"+
    "\10\0\1\67\11\0\2\46\1\0\12\46\1\71\4\46"+
    "\3\0\26\46\10\0\1\67\11\0\2\46\1\0\17\46"+
    "\3\0\1\72\23\46\1\73\1\46\10\0\1\67\11\0"+
    "\2\46\1\0\17\46\3\0\10\46\1\74\15\46\10\0"+
    "\1\67\11\0\2\46\1\0\17\46\3\0\12\46\1\75"+
    "\1\46\1\76\11\46\10\0\1\67\11\0\2\46\1\0"+
    "\17\46\3\0\12\46\1\77\13\46\10\0\1\67\11\0"+
    "\2\46\1\0\17\46\3\0\13\46\1\100\12\46\10\0"+
    "\1\67\11\0\2\46\1\0\17\46\3\0\1\101\25\46"+
    "\10\0\1\67\11\0\2\46\1\0\17\46\3\0\20\46"+
    "\1\102\5\46\10\0\1\67\11\0\2\46\1\0\17\46"+
    "\3\0\23\46\1\103\2\46\10\0\1\67\11\0\2\46"+
    "\1\0\17\46\3\0\17\46\1\104\6\46\10\0\1\67"+
    "\11\0\2\46\1\0\17\46\3\0\16\46\1\105\7\46"+
    "\10\0\1\67\11\0\2\46\1\0\17\46\3\0\3\46"+
    "\1\106\22\46\37\0\1\107\75\0\1\110\44\0\1\67"+
    "\11\0\2\46\1\0\2\46\1\111\14\46\3\0\26\46"+
    "\10\0\1\67\11\0\2\46\1\0\12\46\1\112\4\46"+
    "\3\0\26\46\10\0\1\67\11\0\2\46\1\0\17\46"+
    "\3\0\17\46\1\113\6\46\10\0\1\67\11\0\2\46"+
    "\1\0\17\46\2\0\1\114\4\46\1\115\21\46\10\0"+
    "\1\67\11\0\2\46\1\0\17\46\3\0\2\46\1\116"+
    "\23\46\10\0\1\67\11\0\2\46\1\0\17\46\3\0"+
    "\20\46\1\117\5\46\10\0\1\67\11\0\2\46\1\0"+
    "\17\46\3\0\5\46\1\120\20\46\10\0\1\67\11\0"+
    "\2\46\1\0\17\46\3\0\12\46\1\121\13\46\10\0"+
    "\1\67\11\0\2\46\1\0\17\46\3\0\4\46\1\122"+
    "\21\46\10\0\1\67\11\0\2\46\1\0\17\46\3\0"+
    "\25\46\1\123\10\0\1\67\11\0\2\46\1\0\15\46"+
    "\1\124\1\125\3\0\26\46\10\0\1\67\11\0\2\46"+
    "\1\0\17\46\3\0\20\46\1\126\5\46\10\0\1\67"+
    "\11\0\2\46\1\0\17\46\3\0\6\46\1\127\17\46"+
    "\10\0\1\67\11\0\2\46\1\0\17\46\3\0\4\46"+
    "\1\130\21\46\10\0\1\67\11\0\2\46\1\0\17\46"+
    "\3\0\4\46\1\131\21\46\41\0\1\132\43\0\1\67"+
    "\11\0\2\46\1\0\11\46\1\133\5\46\3\0\26\46"+
    "\10\0\1\134\11\0\2\46\1\0\17\46\3\0\26\46"+
    "\10\0\1\67\11\0\2\46\1\0\17\46\3\0\3\46"+
    "\1\135\22\46\51\0\1\136\12\0\1\137\20\0\1\67"+
    "\11\0\2\46\1\0\17\46\3\0\20\46\1\140\5\46"+
    "\10\0\1\67\11\0\2\46\1\0\17\46\3\0\11\46"+
    "\1\141\14\46\10\0\1\142\11\0\2\46\1\0\17\46"+
    "\3\0\26\46\10\0\1\67\11\0\2\46\1\0\17\46"+
    "\3\0\10\46\1\143\15\46\10\0\1\67\11\0\2\46"+
    "\1\0\17\46\2\0\1\144\26\46\10\0\1\145\11\0"+
    "\2\46\1\0\17\46\3\0\26\46\10\0\1\67\11\0"+
    "\2\46\1\0\17\46\3\0\4\46\1\146\21\46\10\0"+
    "\1\147\11\0\2\46\1\0\17\46\3\0\26\46\10\0"+
    "\1\150\11\0\2\46\1\0\17\46\3\0\26\46\10\0"+
    "\1\151\11\0\2\46\1\0\17\46\3\0\26\46\10\0"+
    "\1\67\11\0\2\46\1\0\17\46\3\0\4\46\1\152"+
    "\21\46\10\0\1\153\11\0\2\46\1\0\17\46\3\0"+
    "\26\46\10\0\1\67\11\0\2\46\1\0\17\46\3\0"+
    "\5\46\1\154\20\46\10\0\1\155\11\0\2\46\1\0"+
    "\17\46\3\0\26\46\10\0\1\156\11\0\2\46\1\0"+
    "\17\46\3\0\26\46\64\0\1\157\73\0\1\160\21\0"+
    "\1\161\11\0\2\46\1\0\17\46\3\0\26\46\10\0"+
    "\1\67\11\0\2\46\1\0\17\46\2\0\1\162\26\46"+
    "\10\0\1\67\11\0\2\46\1\0\17\46\3\0\6\46"+
    "\1\163\17\46\51\0\1\164\33\0\1\67\11\0\2\46"+
    "\1\0\17\46\3\0\17\46\1\165\6\46\10\0\1\67"+
    "\11\0\2\46\1\0\17\46\3\0\21\46\1\166\4\46"+
    "\10\0\1\67\11\0\2\46\1\0\17\46\3\0\10\46"+
    "\1\167\15\46\61\0\1\170\61\0\1\171\77\0\1\172"+
    "\33\0\1\173\11\0\2\46\1\0\17\46\3\0\26\46"+
    "\64\0\1\174\20\0\1\175\11\0\2\46\1\0\17\46"+
    "\2\0\1\176\26\46\10\0\1\67\11\0\2\46\1\0"+
    "\17\46\2\0\1\177\20\46\1\200\5\46\10\0\1\67"+
    "\11\0\2\46\1\0\17\46\3\0\14\46\1\201\11\46"+
    "\64\0\1\202\100\0\1\203\70\0\1\204\71\0\1\205"+
    "\64\0\1\206\74\0\1\207\33\0\1\210\11\0\2\46"+
    "\1\0\17\46\3\0\26\46\10\0\1\67\11\0\2\46"+
    "\1\0\17\46\3\0\4\46\1\211\21\46\66\0\1\212"+
    "\55\0\1\213\106\0\1\214\77\0\1\215\74\0\1\216"+
    "\74\0\1\217\20\0\1\67\11\0\2\46\1\0\17\46"+
    "\3\0\3\46\1\220\22\46\10\0\1\221\152\0\1\222"+
    "\72\0\1\223\76\0\1\224\67\0\1\225\74\0\1\226"+
    "\23\0\1\67\11\0\2\46\1\0\17\46\2\0\1\227"+
    "\26\46\55\0\1\230\105\0\1\231\16\0\1\232\150\0"+
    "\1\233\74\0\1\234\61\0\1\235\76\0\1\236\31\0"+
    "\1\237\152\0\1\240\74\0\1\241\72\0\1\242\100\0"+
    "\1\243\14\0\1\244\74\0\1\245\145\0\1\246\61\0"+
    "\1\247\112\0\1\250\61\0\1\251\111\0\1\252\72\0"+
    "\1\253\20\0\1\254\145\0\1\255\77\0\1\256\76\0"+
    "\1\257\16\0\1\260\70\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8418];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\7\11\2\1\1\11\2\1\4\11"+
    "\13\0\1\1\21\0\1\1\2\0\1\11\17\0\1\11"+
    "\22\0\1\11\1\0\1\11\5\0\1\11\2\0\1\11"+
    "\1\0\3\11\1\0\1\11\1\0\2\11\2\0\1\11"+
    "\11\0\1\11\1\0\1\11\12\0\1\11\10\0\1\11"+
    "\10\0\1\11\4\0\1\11\4\0\2\11\6\0\1\11"+
    "\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[176];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

    private Token token(TokenType type) {
        return new Token(type, yyline + 1, yycolumn + 1);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
  	yyline=1;
	yycolumn=1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return token(TokenType.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Token(TokenType.ERROR,yyline,yycolumn,yytext());
            }
          // fall through
          case 42: break;
          case 2:
            { /*Ignorar*/
            }
          // fall through
          case 43: break;
          case 3:
            { return new Token(TokenType.COMILLAS,yyline,yycolumn,yytext());
            }
          // fall through
          case 44: break;
          case 4:
            { return new Token(TokenType.PARENTESIS_A,yyline,yycolumn,yytext());
            }
          // fall through
          case 45: break;
          case 5:
            { return new Token(TokenType.PARENTESIS_C,yyline,yycolumn,yytext());
            }
          // fall through
          case 46: break;
          case 6:
            { return new Token(TokenType.MULTIPLICACION,yyline,yycolumn,yytext());
            }
          // fall through
          case 47: break;
          case 7:
            { return new Token(TokenType.SUMA,yyline,yycolumn,yytext());
            }
          // fall through
          case 48: break;
          case 8:
            { return new Token(TokenType.COMA,yyline,yycolumn,yytext());
            }
          // fall through
          case 49: break;
          case 9:
            { return new Token(TokenType.RESTA,yyline,yycolumn,yytext());
            }
          // fall through
          case 50: break;
          case 10:
            { return new Token(TokenType.DIVISION,yyline,yycolumn,yytext());
            }
          // fall through
          case 51: break;
          case 11:
            { return new Token(TokenType.ENTERO,yyline,yycolumn,yytext());
            }
          // fall through
          case 52: break;
          case 12:
            { return new Token(TokenType.DOSPUNTOS,yyline,yycolumn,yytext());
            }
          // fall through
          case 53: break;
          case 13:
            { return new Token(TokenType.CORCHETE_A,yyline,yycolumn,yytext());
            }
          // fall through
          case 54: break;
          case 14:
            { return new Token(TokenType.CORCHETE_C,yyline,yycolumn,yytext());
            }
          // fall through
          case 55: break;
          case 15:
            { return new Token(TokenType.LLAVE_A,yyline,yycolumn,yytext());
            }
          // fall through
          case 56: break;
          case 16:
            { return new Token(TokenType.LLAVE_C,yyline,yycolumn,yytext());
            }
          // fall through
          case 57: break;
          case 17:
            { return new Token(TokenType.COLOR,yyline,yycolumn,yytext());
            }
          // fall through
          case 58: break;
          case 18:
            { return new Token(TokenType.DECIMAL,yyline,yycolumn,yytext());
            }
          // fall through
          case 59: break;
          case 19:
            { return new Token(TokenType.NOMBRE,yyline,yycolumn,yytext());
            }
          // fall through
          case 60: break;
          case 20:
            { return new Token(TokenType.CEIL,yyline,yycolumn,yytext());
            }
          // fall through
          case 61: break;
          case 21:
            { return new Token(TokenType.FLOOR,yyline,yycolumn,yytext());
            }
          // fall through
          case 62: break;
          case 22:
            { return new Token(TokenType.HALL,yyline,yycolumn,yytext());
            }
          // fall through
          case 63: break;
          case 23:
            { return new Token(TokenType.COLS,yyline,yycolumn,yytext());
            }
          // fall through
          case 64: break;
          case 24:
            { return new Token(TokenType.NAME,yyline,yycolumn,yytext());
            }
          // fall through
          case 65: break;
          case 25:
            { return new Token(TokenType.POSX,yyline,yycolumn,yytext());
            }
          // fall through
          case 66: break;
          case 26:
            { return new Token(TokenType.POSY,yyline,yycolumn,yytext());
            }
          // fall through
          case 67: break;
          case 27:
            { return new Token(TokenType.ROWS,yyline,yycolumn,yytext());
            }
          // fall through
          case 68: break;
          case 28:
            { return new Token(TokenType.TYPE,yyline,yycolumn,yytext());
            }
          // fall through
          case 69: break;
          case 29:
            { return new Token(TokenType.BRICK,yyline,yycolumn,yytext());
            }
          // fall through
          case 70: break;
          case 30:
            { return new Token(TokenType.BOARD,yyline,yycolumn,yytext());
            }
          // fall through
          case 71: break;
          case 31:
            { return new Token(TokenType.BOXES,yyline,yycolumn,yytext());
            }
          // fall through
          case 72: break;
          case 32:
            { return new Token(TokenType.CONFIG,yyline,yycolumn,yytext());
            }
          // fall through
          case 73: break;
          case 33:
            { return new Token(TokenType.PLAYER,yyline,yycolumn,yytext());
            }
          // fall through
          case 74: break;
          case 34:
            { return new Token(TokenType.TARGETS,yyline,yycolumn,yytext());
            }
          // fall through
          case 75: break;
          case 35:
            { return new Token(TokenType.BOX_COLOR,yyline,yycolumn,yytext());
            }
          // fall through
          case 76: break;
          case 36:
            { return new Token(TokenType.HALL_COLOR,yyline,yycolumn,yytext());
            }
          // fall through
          case 77: break;
          case 37:
            { return new Token(TokenType.BRICK_COLOR,yyline,yycolumn,yytext());
            }
          // fall through
          case 78: break;
          case 38:
            { return new Token(TokenType.PLAYER_COLOR,yyline,yycolumn,yytext());
            }
          // fall through
          case 79: break;
          case 39:
            { return new Token(TokenType.TARGET_COLOR,yyline,yycolumn,yytext());
            }
          // fall through
          case 80: break;
          case 40:
            { return new Token(TokenType.UNDEFINED_COLOR,yyline,yycolumn,yytext());
            }
          // fall through
          case 81: break;
          case 41:
            { return new Token(TokenType.BOX_ON_TARGET_COLOR,yyline,yycolumn,yytext());
            }
          // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
