
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.yefrig.boxworldserver.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int DOSPUNTOS = 39;
  public static final int BRICK_COLOR = 11;
  public static final int NOMBRE = 32;
  public static final int ENTERO = 28;
  public static final int RESTA = 34;
  public static final int TARGETS = 20;
  public static final int CORCHETE_C = 23;
  public static final int BOX_COLOR = 8;
  public static final int TARGET_COLOR = 10;
  public static final int CORCHETE_A = 22;
  public static final int LLAVE_C = 27;
  public static final int LLAVE_A = 26;
  public static final int ROWS = 5;
  public static final int FLOOR = 30;
  public static final int CONFIG = 7;
  public static final int TYPE = 18;
  public static final int BOX_ON_TARGET_COLOR = 9;
  public static final int BOARD = 15;
  public static final int SUMA = 33;
  public static final int HALL = 3;
  public static final int HALL_COLOR = 12;
  public static final int EOF = 0;
  public static final int BRICK = 2;
  public static final int PLAYER = 21;
  public static final int DECIMAL = 29;
  public static final int COMILLAS = 38;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int ERROR = 41;
  public static final int NAME = 4;
  public static final int COLOR = 37;
  public static final int POSY = 17;
  public static final int POSX = 16;
  public static final int COLS = 6;
  public static final int PARENTESIS_C = 25;
  public static final int PARENTESIS_A = 24;
  public static final int BOXES = 19;
  public static final int CEIL = 31;
  public static final int DIVISION = 36;
  public static final int UNDEFINED_COLOR = 13;
  public static final int MULTIPLICACION = 35;
  public static final int PLAYER_COLOR = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BRICK",
  "HALL",
  "NAME",
  "ROWS",
  "COLS",
  "CONFIG",
  "BOX_COLOR",
  "BOX_ON_TARGET_COLOR",
  "TARGET_COLOR",
  "BRICK_COLOR",
  "HALL_COLOR",
  "UNDEFINED_COLOR",
  "PLAYER_COLOR",
  "BOARD",
  "POSX",
  "POSY",
  "TYPE",
  "BOXES",
  "TARGETS",
  "PLAYER",
  "CORCHETE_A",
  "CORCHETE_C",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "ENTERO",
  "DECIMAL",
  "FLOOR",
  "CEIL",
  "NOMBRE",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "COLOR",
  "COMILLAS",
  "DOSPUNTOS",
  "COMA",
  "ERROR"
  };
}

